#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__


#define TRANSITION_TIME					0.2f
#define TRANSITION_TIME_MOVE_IN_R		0.2f
#define TRANSITION_TIME_GAME_OVER		0.1f

#define DISPLAY_TIME_SPLASH_SCENE		0.5f



#define NUM_FRAME_ANIMATION_JUMP		16
#define ANIMATION_DELAY_TIME_JUMP		0.05f

#define TIME_TOUCH_JUMP					270
#define MRJUMP_RUNNING_SPEED			6.0f
#define MRJUMP_JUMPING_DUARATION		0.25f
#define MRJUMP_JUMPING_HEIGHT			10.0f



#define GAME_GRAVITY					0.0f, -920.0f


#define MRJUMP_COLLISION_BITMASK		0x0001
#define GROUND_COLLISION_BITMASK		0x0002
#define HAZARD_COLLISION_BITMASK		0x0003

#define MUSIC_EFFECT_LEVEL_TURN_OFF		-1


#define FILEPATH_BACKGROUND_MUSIC				"Mr_Jump_Background.wav"
#define FILEPATH_LEVEL_MUSIC_EFFECT				"Mr_Jump_Music_Level_1.wav"
#define FILEPATH_BUTTON_MUSIC_EFFECT			"Mr_Jump_Button_Music_Effect.wav"


#define USER_DATA_KEY_MUSIC_EFFECT				"USERDATAKEYMUSICEFFECT"

#define USER_DATA_KEY_SCORE_PERCENT				"USERDATAKEYSCOREPERCENT"
#define USER_DATA_KEY_NUMBER_JUMPS				"USERDATAKEYNUMBERJUMPS"
								
#define USER_DATA_KEY_IS_PLAY_BACKGROUND_MUSIC	"USERDATAKEYISBACKGROUNDMUSIC"
#define USER_DATA_KEY_IS_PLAY_AUDIO_EFFECT		"USERDATAKEYISPLAYAUDIOEFFECT"



enum USER_SETUP_AUDIO {
	TURN_ON,
	TURN_OFF
};


enum LEVEL_NAME {
	LEVEL_1 = 1,
	LEVEL_2
};

enum TAG_ZORDER {
	UI, 
	MAP,
	PLAYER,
	GAMEOVERLAYER
};




#endif // __DEFINITIONS_H__
